"""empty message

Revision ID: 2622ff6df1d4
Revises: None
Create Date: 2016-10-06 14:55:55.616157

"""

# revision identifiers, used by Alembic.
revision = '2622ff6df1d4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from app.base.guid import GUID


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_blogpost',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pages_page',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_page')
    op.drop_table('blog_blogpost')
    ### end Alembic commands ###
