"""empty message

Revision ID: c928f1b41326
Revises: fc5af07f66f
Create Date: 2016-09-26 13:56:47.500788

"""

# revision identifiers, used by Alembic.
revision = 'c928f1b41326'
down_revision = 'fc5af07f66f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_perm')
    op.drop_table('auth_user')
    op.drop_table('auth_perm_assoc')
    op.create_unique_constraint(None, 'blog_blogpost', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_blogpost', type_='unique')
    op.create_table('auth_perm_assoc',
    sa.Column('auth_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auth_perm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auth_perm_id'], [u'auth_perm.id'], name=u'auth_perm_assoc_auth_perm_id_fkey'),
    sa.ForeignKeyConstraint(['auth_user_id'], [u'auth_user.id'], name=u'auth_perm_assoc_auth_user_id_fkey')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'auth_user_pkey'),
    sa.UniqueConstraint('username', name=u'auth_user_username_key')
    )
    op.create_table('auth_perm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'auth_perm_pkey')
    )
    ### end Alembic commands ###
