#!/usr/bin/env python

import requests
import os
SlackWebhookURL = os.getenv['SLACK_WEBHOOK_URL']
SlackMessage = "App: " + os.getenv['APP_ID'] + "\nInstance Id: " + os.getenv['INSTANCE_ID'] + "\nInstance Type: " + os.getenv['INSTANCE_TYPE'] + "\nCommit Id: " + os.getenv['COMMIT_ID'] + "\nInstance Number: " + os.getenv['INSTANCE_NUMBER']
payload = {'text': SlackMessage}
r = requests.post(SlackWebhookURL, data=payload)
